import banCommentsPlugin from "./index.js";

export default [
  {
    exclude: ["*.d.ts"],
    files: [
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
      "**/*.ts",
      "**/*.tsx",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      "ban-comments": banCommentsPlugin,
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      "no-console": "warn",
      "no-debugger": "error",
      "no-alert": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-with": "error",
      strict: ["error", "global"],
      curly: "error",
      eqeqeq: ["error", "always"],
      "no-empty": "error",
      "no-empty-function": "error",
      "no-extra-semi": "error",
      "no-unreachable": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-redeclare": "error",
      "no-shadow": "error",
      "no-use-before-define": "error",
      "prefer-const": "error",
      "no-var": "error",
      "arrow-spacing": "error",
      "comma-dangle": ["error", "never"],
      "comma-spacing": "error",
      indent: ["error", 2],
      quotes: ["error", "single"],
      semi: ["error", "always"],
      "space-before-blocks": "error",
      "space-infix-ops": "error",
      "keyword-spacing": "error",
      "brace-style": "error",
      camelcase: "error",
      "consistent-this": ["error", "that"],
      "func-names": "error",
      "max-depth": ["error", 4],
      "max-len": ["error", { code: 120 }],
      "max-params": ["error", 4],
      "new-cap": "error",
      "no-array-constructor": "error",
      "no-lonely-if": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-multiple-empty-lines": ["error", { max: 2 }],
      "no-nested-ternary": "error",
      "no-trailing-spaces": "error",
      "no-unneeded-ternary": "error",
      "object-curly-spacing": ["error", "always"],
      "one-var": ["error", "never"],
      "operator-linebreak": ["error", "before"],
      "padded-blocks": ["error", "never"],
      "quote-props": ["error", "as-needed"],
      "space-before-function-paren": ["error", "never"],
      "space-in-parens": ["error", "never"],
      "spaced-comment": ["error", "always"],

      "ban-comments/ban-comments": "error",
    },
  },
  {
    files: ["test/**/*.js"],
    rules: {
      "no-console": "off",

      "max-len": ["error", { code: 150 }],
    },
  },
];
